
# txt files generated by make
resource "observe_board" "database_monitoring" {
  for_each = toset(["set", "singleton"])
  dataset  = observe_dataset.cloudsql.oid
  name     = "Cloud SQL Instance Monitoring"
  type     = each.value
  json = templatefile("${path.module}/boards/SummaryBoard.json", {
    summary_txt   = file("${path.module}/boards/summary.txt"),
    summary_notes = file("${path.module}/boards/summary_notes.txt")
  })
}
