
######################
# This file is autogenerated
# run serviceUtilities.py in service directory to create this file
# serviceUtilities.py -h for list of commands and options
######################
locals { metrics_definitions = {
  active_directory_domain_reachable = {
    type               = "gauge"
    description        = <<-EOF
                    Indicates whether the instance is able to ping a domain controller from the connected Managed Active Directory domain. If false, Windows Authentication may not work as expected.
                EOF
    launchStage        = "ALPHA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "active_directory"
    google_metric_path = "cloudsql.googleapis.com/database/active_directory/domain_reachable"
    label              = "Active Directory domain reachable"
    unit               = ""
    metricBin          = "['database']"
    valuetype          = "BOOL"
    dataBase           = "ALL"
  }
  active_directory_instance_available = {
    type               = "gauge"
    description        = <<-EOF
                    Indicates whether the instance is currently available using Windows Authentication.
                EOF
    launchStage        = "ALPHA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "active_directory"
    google_metric_path = "cloudsql.googleapis.com/database/active_directory/instance_available"
    label              = "Windows Authentication available"
    unit               = ""
    metricBin          = "['database']"
    valuetype          = "BOOL"
    dataBase           = "ALL"
  }
  auto_failover_request_count = {
    type               = "delta"
    description        = <<-EOF
                    Delta of number of instance auto-failover requests.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "cloudsql.googleapis.com/database/auto_failover_request_count"
    label              = "Auto-failover Requests"
    unit               = "1"
    metricBin          = "['database']"
    valuetype          = "INT64"
    dataBase           = "ALL"
  }
  available_for_failover = {
    type               = "gauge"
    description        = <<-EOF
                    This is greater than 0 if the failover operation is available on the instance.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "cloudsql.googleapis.com/database/available_for_failover"
    label              = "Available for failover"
    unit               = "1"
    metricBin          = "['database']"
    valuetype          = "INT64"
    dataBase           = "ALL"
  }
  cpu_reserved_cores = {
    type               = "gauge"
    description        = <<-EOF
                    Number of cores reserved for the database.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "cpu"
    google_metric_path = "cloudsql.googleapis.com/database/cpu/reserved_cores"
    label              = "CPU reserved cores"
    unit               = "1"
    metricBin          = "['database']"
    valuetype          = "DOUBLE"
    dataBase           = "ALL"
  }
  cpu_usage_time = {
    type               = "delta"
    description        = <<-EOF
                    Cumulative CPU usage time in seconds.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "cpu"
    google_metric_path = "cloudsql.googleapis.com/database/cpu/usage_time"
    label              = "CPU usage"
    unit               = "s{CPU}"
    metricBin          = "['database']"
    valuetype          = "DOUBLE"
    dataBase           = "ALL"
  }
  cpu_utilization = {
    type               = "gauge"
    description        = <<-EOF
                    Current CPU utilization represented as a percentage of the reserved CPU that is currently in use. Values are typically numbers between 0.0 and 1.0 but might exceed 1.0. Charts display the values as a percentage between 0% and 100% or more.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "cpu"
    google_metric_path = "cloudsql.googleapis.com/database/cpu/utilization"
    label              = "CPU utilization"
    unit               = "10^2.%"
    metricBin          = "['database']"
    valuetype          = "DOUBLE"
    dataBase           = "ALL"
  }
  disk_bytes_used = {
    type               = "gauge"
    description        = <<-EOF
                    Data utilization in bytes.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "disk"
    google_metric_path = "cloudsql.googleapis.com/database/disk/bytes_used"
    label              = "Bytes used"
    unit               = "By"
    metricBin          = "['database']"
    valuetype          = "INT64"
    dataBase           = "ALL"
  }
  disk_bytes_used_by_data_type = {
    type               = "gauge"
    description        = <<-EOF
                    Data utilization in bytes.
                EOF
    launchStage        = "BETA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "disk"
    google_metric_path = "cloudsql.googleapis.com/database/disk/bytes_used_by_data_type"
    label              = "Bytes used"
    unit               = "By"
    metricBin          = "['database']"
    valuetype          = "INT64"
    dataBase           = "ALL"
  }
  disk_quota = {
    type               = "gauge"
    description        = <<-EOF
                    Maximum data disk size in bytes.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "disk"
    google_metric_path = "cloudsql.googleapis.com/database/disk/quota"
    label              = "Disk quota"
    unit               = "By"
    metricBin          = "['database']"
    valuetype          = "INT64"
    dataBase           = "ALL"
  }
  disk_read_ops_count = {
    type               = "delta"
    description        = <<-EOF
                    Delta count of data disk read IO operations.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "disk"
    google_metric_path = "cloudsql.googleapis.com/database/disk/read_ops_count"
    label              = "Disk read IO"
    unit               = "1"
    metricBin          = "['database']"
    valuetype          = "INT64"
    dataBase           = "ALL"
  }
  disk_utilization = {
    type               = "gauge"
    description        = <<-EOF
                    The fraction of the disk quota that is currently in use.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "disk"
    google_metric_path = "cloudsql.googleapis.com/database/disk/utilization"
    label              = "Disk utilization"
    unit               = "1"
    metricBin          = "['database']"
    valuetype          = "DOUBLE"
    dataBase           = "ALL"
  }
  disk_write_ops_count = {
    type               = "delta"
    description        = <<-EOF
                    Delta count of data disk write IO operations.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "disk"
    google_metric_path = "cloudsql.googleapis.com/database/disk/write_ops_count"
    label              = "Disk write IO"
    unit               = "1"
    metricBin          = "['database']"
    valuetype          = "INT64"
    dataBase           = "ALL"
  }
  instance_state = {
    type               = "gauge"
    description        = <<-EOF
                    The current serving state of the Cloud SQL instance.
Because there are seven possible states, seven data points are returned.
Each of them has a different field value representing each state.
Only the one that matches the current state of the instance is TRUE. All the others are FALSE.
The state can be one of the following:
RUNNING:  The instance is running, or is ready to run when accessed.
SUSPENDED: The instance is not available, for example due to problems with billing.
RUNNABLE: The instance has been stopped by owner. It is not currently running, but it's ready to be restarted.
PENDING_CREATE: The instance is being created.
MAINTENANCE: The instance is down for maintenance.
FAILED: The instance creation failed.
UNKNOWN_STATE: The state of the instance is unknown.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "cloudsql.googleapis.com/database/instance_state"
    label              = "Instance state"
    unit               = ""
    metricBin          = "['database']"
    valuetype          = "BOOL"
    dataBase           = "ALL"
  }
  memory_quota = {
    type               = "gauge"
    description        = <<-EOF
                    Maximum RAM size in bytes.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "memory"
    google_metric_path = "cloudsql.googleapis.com/database/memory/quota"
    label              = "Memory quota"
    unit               = "By"
    metricBin          = "['database']"
    valuetype          = "INT64"
    dataBase           = "ALL"
  }
  memory_total_usage = {
    type               = "gauge"
    description        = <<-EOF
                    Total RAM usage in bytes. This metric reports the RAM usage of the database process, including the buffer/cache.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "memory"
    google_metric_path = "cloudsql.googleapis.com/database/memory/total_usage"
    label              = "Total memory usage"
    unit               = "By"
    metricBin          = "['database']"
    valuetype          = "INT64"
    dataBase           = "ALL"
  }
  memory_usage = {
    type               = "gauge"
    description        = <<-EOF
                    RAM usage in bytes. This metric reports the RAM usage of the server, excluding the buffer/cache.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "memory"
    google_metric_path = "cloudsql.googleapis.com/database/memory/usage"
    label              = "Memory usage"
    unit               = "By"
    metricBin          = "['database']"
    valuetype          = "INT64"
    dataBase           = "ALL"
  }
  memory_utilization = {
    type               = "gauge"
    description        = <<-EOF
                    The fraction of the memory quota that is currently in use.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "memory"
    google_metric_path = "cloudsql.googleapis.com/database/memory/utilization"
    label              = "Memory utilization"
    unit               = "1"
    metricBin          = "['database']"
    valuetype          = "DOUBLE"
    dataBase           = "ALL"
  }
  mysql_innodb_buffer_pool_pages_dirty = {
    type               = "gauge"
    description        = <<-EOF
                    Number of unflushed pages in the InnoDB buffer pool.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "mysql"
    google_metric_path = "cloudsql.googleapis.com/database/mysql/innodb_buffer_pool_pages_dirty"
    label              = "InnoDB dirty pages"
    unit               = "1"
    metricBin          = "['database']"
    valuetype          = "INT64"
    dataBase           = "mysql"
  }
  mysql_innodb_buffer_pool_pages_free = {
    type               = "gauge"
    description        = <<-EOF
                    Number of unused pages in the InnoDB buffer pool.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "mysql"
    google_metric_path = "cloudsql.googleapis.com/database/mysql/innodb_buffer_pool_pages_free"
    label              = "InnoDB free pages"
    unit               = "1"
    metricBin          = "['database']"
    valuetype          = "INT64"
    dataBase           = "mysql"
  }
  mysql_innodb_buffer_pool_pages_total = {
    type               = "gauge"
    description        = <<-EOF
                    Total number of pages in the InnoDB buffer pool.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "mysql"
    google_metric_path = "cloudsql.googleapis.com/database/mysql/innodb_buffer_pool_pages_total"
    label              = "InnoDB total pages"
    unit               = "1"
    metricBin          = "['database']"
    valuetype          = "INT64"
    dataBase           = "mysql"
  }
  mysql_innodb_data_fsyncs = {
    type               = "delta"
    description        = <<-EOF
                    Delta count of InnoDB fsync calls.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "mysql"
    google_metric_path = "cloudsql.googleapis.com/database/mysql/innodb_data_fsyncs"
    label              = "InnoDB fsync calls"
    unit               = "1"
    metricBin          = "['database']"
    valuetype          = "INT64"
    dataBase           = "mysql"
  }
  mysql_innodb_os_log_fsyncs = {
    type               = "delta"
    description        = <<-EOF
                    Delta count of InnoDB fsync calls to the log file.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "mysql"
    google_metric_path = "cloudsql.googleapis.com/database/mysql/innodb_os_log_fsyncs"
    label              = "InnoDB log fsync calls"
    unit               = "1"
    metricBin          = "['database']"
    valuetype          = "INT64"
    dataBase           = "mysql"
  }
  mysql_innodb_pages_read = {
    type               = "delta"
    description        = <<-EOF
                    Delta count of InnoDB pages read.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "mysql"
    google_metric_path = "cloudsql.googleapis.com/database/mysql/innodb_pages_read"
    label              = "InnoDB pages read"
    unit               = "1"
    metricBin          = "['database']"
    valuetype          = "INT64"
    dataBase           = "mysql"
  }
  mysql_innodb_pages_written = {
    type               = "delta"
    description        = <<-EOF
                    Delta count of InnoDB pages written.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "mysql"
    google_metric_path = "cloudsql.googleapis.com/database/mysql/innodb_pages_written"
    label              = "InnoDB pages written"
    unit               = "1"
    metricBin          = "['database']"
    valuetype          = "INT64"
    dataBase           = "mysql"
  }
  mysql_queries = {
    type               = "delta"
    description        = <<-EOF
                    Delta count of statements executed by the server.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "mysql"
    google_metric_path = "cloudsql.googleapis.com/database/mysql/queries"
    label              = "Queries"
    unit               = "1"
    metricBin          = "['database']"
    valuetype          = "INT64"
    dataBase           = "mysql"
  }
  mysql_questions = {
    type               = "delta"
    description        = <<-EOF
                    Delta count of statements executed by the server sent by the client.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "mysql"
    google_metric_path = "cloudsql.googleapis.com/database/mysql/questions"
    label              = "Questions"
    unit               = "1"
    metricBin          = "['database']"
    valuetype          = "INT64"
    dataBase           = "mysql"
  }
  mysql_received_bytes_count = {
    type               = "delta"
    description        = <<-EOF
                    Delta count of bytes received by MySQL process.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "mysql"
    google_metric_path = "cloudsql.googleapis.com/database/mysql/received_bytes_count"
    label              = "Network bytes received by MySQL"
    unit               = "By"
    metricBin          = "['database']"
    valuetype          = "INT64"
    dataBase           = "mysql"
  }
  available_for_failover = {
    type               = "gauge"
    description        = <<-EOF
                    This is greater than 0 if the failover operation is available on the master instance.master. The metric is deprecated.  Please use cloudsql.googleapis.com/database/available_for_failover instead
                EOF
    launchStage        = "BAD_VAL-5"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "cloudsql.googleapis.com/database/mysql/replication/available_for_failover"
    label              = "Available for failover Deprecated"
    unit               = "1"
    metricBin          = "['']"
    valuetype          = "INT64"
    dataBase           = "mysql"
  }
  last_io_errno = {
    type               = "gauge"
    description        = <<-EOF
                    The error number of the most recent error that caused the I/O thread to stop.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "cloudsql.googleapis.com/database/mysql/replication/last_io_errno"
    label              = "Last I/O thread error number."
    unit               = "1"
    metricBin          = "['']"
    valuetype          = "INT64"
    dataBase           = "mysql"
  }
  last_sql_errno = {
    type               = "gauge"
    description        = <<-EOF
                    The error number of the most recent error that caused the SQL thread to stop.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "cloudsql.googleapis.com/database/mysql/replication/last_sql_errno"
    label              = "Last SQL thread error number."
    unit               = "1"
    metricBin          = "['']"
    valuetype          = "INT64"
    dataBase           = "mysql"
  }
  seconds_behind_master = {
    type               = "gauge"
    description        = <<-EOF
                    Number of seconds the read replica is behind its primary approximation.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "cloudsql.googleapis.com/database/mysql/replication/seconds_behind_master"
    label              = "Replication lag"
    unit               = "s"
    metricBin          = "['']"
    valuetype          = "INT64"
    dataBase           = "mysql"
  }
  slave_io_running = {
    type               = "gauge"
    description        = <<-EOF
                    Indicates whether the I/O thread for reading the primary's binary log is running. Possible values are Yes, No and Connecting.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "cloudsql.googleapis.com/database/mysql/replication/slave_io_running"
    label              = "Slave I/O thread running"
    unit               = ""
    metricBin          = "['']"
    valuetype          = "STRING"
    dataBase           = "mysql"
  }
  slave_io_running_state = {
    type               = "gauge"
    description        = <<-EOF
                    Indicates whether the I/O thread for reading the primary's binary log is running. Possible values are Yes, No and Connecting, and the values are exposed through the 'state' field.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "cloudsql.googleapis.com/database/mysql/replication/slave_io_running_state"
    label              = "Slave I/O thread running state"
    unit               = ""
    metricBin          = "['']"
    valuetype          = "BOOL"
    dataBase           = "mysql"
  }
  slave_sql_running = {
    type               = "gauge"
    description        = <<-EOF
                    Indicates whether the SQL thread for executing events in the relay log is running.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "cloudsql.googleapis.com/database/mysql/replication/slave_sql_running"
    label              = "Slave SQL thread running"
    unit               = ""
    metricBin          = "['']"
    valuetype          = "STRING"
    dataBase           = "mysql"
  }
  slave_sql_running_state = {
    type               = "gauge"
    description        = <<-EOF
                    Indicates whether the SQL thread for executing events in the relay log is running. Possible values are Yes / No, and the values are exposed through the 'state' field.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "cloudsql.googleapis.com/database/mysql/replication/slave_sql_running_state"
    label              = "Slave SQL thread running state"
    unit               = ""
    metricBin          = "['']"
    valuetype          = "BOOL"
    dataBase           = "mysql"
  }
  mysql_sent_bytes_count = {
    type               = "delta"
    description        = <<-EOF
                    Delta count of bytes sent by MySQL process.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "mysql"
    google_metric_path = "cloudsql.googleapis.com/database/mysql/sent_bytes_count"
    label              = "Network bytes sent by MySQL"
    unit               = "By"
    metricBin          = "['database']"
    valuetype          = "INT64"
    dataBase           = "mysql"
  }
  network_connections = {
    type               = "gauge"
    description        = <<-EOF
                    Number of connections to databases on the Cloud SQL instance. Only applicable to MySQL and SQL Server.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "network"
    google_metric_path = "cloudsql.googleapis.com/database/network/connections"
    label              = "Cloud SQL Connections"
    unit               = "1"
    metricBin          = "['database']"
    valuetype          = "INT64"
    dataBase           = "ALL"
  }
  network_received_bytes_count = {
    type               = "delta"
    description        = <<-EOF
                    Delta count of bytes received through the network.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "network"
    google_metric_path = "cloudsql.googleapis.com/database/network/received_bytes_count"
    label              = "Received bytes"
    unit               = "By"
    metricBin          = "['database']"
    valuetype          = "INT64"
    dataBase           = "ALL"
  }
  network_sent_bytes_count = {
    type               = "delta"
    description        = <<-EOF
                    Delta count of bytes sent through the network.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "network"
    google_metric_path = "cloudsql.googleapis.com/database/network/sent_bytes_count"
    label              = "Sent bytes"
    unit               = "By"
    metricBin          = "['database']"
    valuetype          = "INT64"
    dataBase           = "ALL"
  }
  postgresql_blocks_read_count = {
    type               = "delta"
    description        = <<-EOF
                    Number of disk blocks read by this database. The source field distingushes actual reads from disk versus reads from buffer cache.
                EOF
    launchStage        = "BETA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "postgresql"
    google_metric_path = "cloudsql.googleapis.com/database/postgresql/blocks_read_count"
    label              = "Number of disk blocks read."
    unit               = "1"
    metricBin          = "['database']"
    valuetype          = "INT64"
    dataBase           = "postgresql"
  }
  postgresql_deadlock_count = {
    type               = "delta"
    description        = <<-EOF
                    Number of deadlocks detected for this database.
                EOF
    launchStage        = "BETA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "postgresql"
    google_metric_path = "cloudsql.googleapis.com/database/postgresql/deadlock_count"
    label              = "Deadlocks count"
    unit               = "1"
    metricBin          = "['database']"
    valuetype          = "INT64"
    dataBase           = "postgresql"
  }
  initial_sync_complete = {
    type               = "gauge"
    description        = <<-EOF
                    Whether all databases on the Postgres External Server ES replica have completed the initial sync and are replicating changes from the source.
                EOF
    launchStage        = "ALPHA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "cloudsql.googleapis.com/database/postgresql/external_sync/initial_sync_complete"
    label              = "Initial sync complete"
    unit               = ""
    metricBin          = "['']"
    valuetype          = "BOOL"
    dataBase           = "postgresql"
  }
  max_replica_byte_lag = {
    type               = "gauge"
    description        = <<-EOF
                    Replication lag in bytes for Postgres External Server ES replicas. Aggregated across all DBs on the replica.
                EOF
    launchStage        = "ALPHA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "cloudsql.googleapis.com/database/postgresql/external_sync/max_replica_byte_lag"
    label              = "Max lag bytes"
    unit               = "By"
    metricBin          = "['']"
    valuetype          = "INT64"
    dataBase           = "postgresql"
  }
  execution_time = {
    type               = "cumulativeCounter"
    description        = <<-EOF
                    Accumulated query execution time per user per database. This is the sum of cpu time, io wait time, lock wait time, process context switch, and scheduling for all the processes involved in the query execution.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "cloudsql.googleapis.com/database/postgresql/insights/aggregate/execution_time"
    label              = "Execution time"
    unit               = "us{CPU}"
    metricBin          = "['']"
    valuetype          = "INT64"
    dataBase           = "postgresql"
  }
  io_time = {
    type               = "cumulativeCounter"
    description        = <<-EOF
                    Accumulated IO time per user per database.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "cloudsql.googleapis.com/database/postgresql/insights/aggregate/io_time"
    label              = "IO time"
    unit               = "us"
    metricBin          = "['']"
    valuetype          = "INT64"
    dataBase           = "postgresql"
  }
  latencies = {
    type               = "cumulativeCounter"
    description        = <<-EOF
                    Query latency distribution per user per database.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "cloudsql.googleapis.com/database/postgresql/insights/aggregate/latencies"
    label              = "Latency"
    unit               = "us"
    metricBin          = "['']"
    valuetype          = "DISTRIBUTION"
    dataBase           = "postgresql"
  }
  lock_time = {
    type               = "cumulativeCounter"
    description        = <<-EOF
                    Accumulated lock wait time per user per database.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "cloudsql.googleapis.com/database/postgresql/insights/aggregate/lock_time"
    label              = "Aggregated lock time"
    unit               = "us"
    metricBin          = "['']"
    valuetype          = "INT64"
    dataBase           = "postgresql"
  }
  row_count = {
    type               = "cumulativeCounter"
    description        = <<-EOF
                    Total number of rows affected during query execution.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "cloudsql.googleapis.com/database/postgresql/insights/aggregate/row_count"
    label              = "Affected rows"
    unit               = "1"
    metricBin          = "['']"
    valuetype          = "INT64"
    dataBase           = "postgresql"
  }
  shared_blk_access_count = {
    type               = "cumulativeCounter"
    description        = <<-EOF
                    Shared blocks regular tables and indexed accessed by statement execution.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "cloudsql.googleapis.com/database/postgresql/insights/aggregate/shared_blk_access_count"
    label              = "Shared blocks cache access."
    unit               = "1"
    metricBin          = "['']"
    valuetype          = "INT64"
    dataBase           = "postgresql"
  }
  execution_time = {
    type               = "cumulativeCounter"
    description        = <<-EOF
                    Accumulated execution times per user per database per query.This is the sum of cpu time, io wait time, lock wait time, process context switch, and scheduling for all the processes involved in the query execution.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "cloudsql.googleapis.com/database/postgresql/insights/perquery/execution_time"
    label              = "Per query execution times"
    unit               = "us{CPU}"
    metricBin          = "['']"
    valuetype          = "INT64"
    dataBase           = "postgresql"
  }
  io_time = {
    type               = "cumulativeCounter"
    description        = <<-EOF
                    Accumulated IO time per user per database per query.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "cloudsql.googleapis.com/database/postgresql/insights/perquery/io_time"
    label              = "Per query IO time"
    unit               = "us"
    metricBin          = "['']"
    valuetype          = "INT64"
    dataBase           = "postgresql"
  }
  latencies = {
    type               = "cumulativeCounter"
    description        = <<-EOF
                    Query latency distribution per user per database per query.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "cloudsql.googleapis.com/database/postgresql/insights/perquery/latencies"
    label              = "Per query latency"
    unit               = "us"
    metricBin          = "['']"
    valuetype          = "DISTRIBUTION"
    dataBase           = "postgresql"
  }
  lock_time = {
    type               = "cumulativeCounter"
    description        = <<-EOF
                    Accumulated lock wait time per user per database per query.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "cloudsql.googleapis.com/database/postgresql/insights/perquery/lock_time"
    label              = "Per query lock time"
    unit               = "us"
    metricBin          = "['']"
    valuetype          = "INT64"
    dataBase           = "postgresql"
  }
  row_count = {
    type               = "cumulativeCounter"
    description        = <<-EOF
                    Total number of rows affected during query execution.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "cloudsql.googleapis.com/database/postgresql/insights/perquery/row_count"
    label              = "Per query affected rows"
    unit               = "1"
    metricBin          = "['']"
    valuetype          = "INT64"
    dataBase           = "postgresql"
  }
  shared_blk_access_count = {
    type               = "cumulativeCounter"
    description        = <<-EOF
                    Shared blocks regular tables and indexed accesssed by statement execution.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "cloudsql.googleapis.com/database/postgresql/insights/perquery/shared_blk_access_count"
    label              = "Per query Shared blocks cache access"
    unit               = "1"
    metricBin          = "['']"
    valuetype          = "INT64"
    dataBase           = "postgresql"
  }
  execution_time = {
    type               = "cumulativeCounter"
    description        = <<-EOF
                    Accumulated execution times per user per database per tag.This is the sum of cpu time, io wait time, lock wait time, process context switch, and scheduling for all the processes involved in the query execution.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "cloudsql.googleapis.com/database/postgresql/insights/pertag/execution_time"
    label              = "Per tag execution time"
    unit               = "us{CPU}"
    metricBin          = "['']"
    valuetype          = "INT64"
    dataBase           = "postgresql"
  }
  io_time = {
    type               = "cumulativeCounter"
    description        = <<-EOF
                    Accumulated IO write time per user per database per tag.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "cloudsql.googleapis.com/database/postgresql/insights/pertag/io_time"
    label              = "Per tag IO time"
    unit               = "us"
    metricBin          = "['']"
    valuetype          = "INT64"
    dataBase           = "postgresql"
  }
  latencies = {
    type               = "cumulativeCounter"
    description        = <<-EOF
                    Query latency distribution per user per database per tag.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "cloudsql.googleapis.com/database/postgresql/insights/pertag/latencies"
    label              = "Per tag latency"
    unit               = "us"
    metricBin          = "['']"
    valuetype          = "DISTRIBUTION"
    dataBase           = "postgresql"
  }
  lock_time = {
    type               = "cumulativeCounter"
    description        = <<-EOF
                    Accumulated lock wait time per user per database per tag.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "cloudsql.googleapis.com/database/postgresql/insights/pertag/lock_time"
    label              = "Per tag lock time"
    unit               = "us"
    metricBin          = "['']"
    valuetype          = "INT64"
    dataBase           = "postgresql"
  }
  row_count = {
    type               = "cumulativeCounter"
    description        = <<-EOF
                    Total number of rows affected during query execution.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "cloudsql.googleapis.com/database/postgresql/insights/pertag/row_count"
    label              = "Per tag affected rows"
    unit               = "1"
    metricBin          = "['']"
    valuetype          = "INT64"
    dataBase           = "postgresql"
  }
  shared_blk_access_count = {
    type               = "cumulativeCounter"
    description        = <<-EOF
                    Shared blocks regular tables and indexed accessed by statement execution.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "cloudsql.googleapis.com/database/postgresql/insights/pertag/shared_blk_access_count"
    label              = "Per tag shared blocks cache accessed"
    unit               = "1"
    metricBin          = "['']"
    valuetype          = "INT64"
    dataBase           = "postgresql"
  }
  postgresql_num_backends = {
    type               = "gauge"
    description        = <<-EOF
                    Number of connections to the Cloud SQL PostgreSQL instance.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "postgresql"
    google_metric_path = "cloudsql.googleapis.com/database/postgresql/num_backends"
    label              = "PostgreSQL Connections"
    unit               = "1"
    metricBin          = "['database']"
    valuetype          = "INT64"
    dataBase           = "postgresql"
  }
  postgresql_num_backends_by_state = {
    type               = "gauge"
    description        = <<-EOF
                    Number of connections to the Cloud SQL PostgreSQL instance, grouped by its state.
                EOF
    launchStage        = "BETA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "postgresql"
    google_metric_path = "cloudsql.googleapis.com/database/postgresql/num_backends_by_state"
    label              = "PostgreSQL Connections by State"
    unit               = "1"
    metricBin          = "['database']"
    valuetype          = "INT64"
    dataBase           = "postgresql"
  }
  replica_byte_lag = {
    type               = "gauge"
    description        = <<-EOF
                    Replication lag in bytes. Reported from the master per replica.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "cloudsql.googleapis.com/database/postgresql/replication/replica_byte_lag"
    label              = "Lag bytes"
    unit               = "By"
    metricBin          = "['']"
    valuetype          = "INT64"
    dataBase           = "postgresql"
  }
  postgresql_transaction_count = {
    type               = "delta"
    description        = <<-EOF
                    Delta count of number of transactions.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "postgresql"
    google_metric_path = "cloudsql.googleapis.com/database/postgresql/transaction_count"
    label              = "Number of transactions"
    unit               = "1"
    metricBin          = "['database']"
    valuetype          = "INT64"
    dataBase           = "postgresql"
  }
  postgresql_transaction_id_count = {
    type               = "delta"
    description        = <<-EOF
                    Delta count of transaction ID.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "postgresql"
    google_metric_path = "cloudsql.googleapis.com/database/postgresql/transaction_id_count"
    label              = "Transaction ID count"
    unit               = "1"
    metricBin          = "['database']"
    valuetype          = "INT64"
    dataBase           = "postgresql"
  }
  postgresql_transaction_id_utilization = {
    type               = "gauge"
    description        = <<-EOF
                    Current utilization represented as a percentage of transaction IDs consumed by the Cloud SQL PostgreSQL instance. Values are typically numbers between 0.0 and 1.0. Charts display the values as a percentage between 0% and 100%.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "postgresql"
    google_metric_path = "cloudsql.googleapis.com/database/postgresql/transaction_id_utilization"
    label              = "Transaction ID utilization"
    unit               = "10^2.%"
    metricBin          = "['database']"
    valuetype          = "DOUBLE"
    dataBase           = "postgresql"
  }
  postgresql_tuple_size = {
    type               = "gauge"
    description        = <<-EOF
                    Number of tuples rows in the database.
                EOF
    launchStage        = "BETA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "postgresql"
    google_metric_path = "cloudsql.googleapis.com/database/postgresql/tuple_size"
    label              = "Number of tuples rows in the database."
    unit               = "1"
    metricBin          = "['database']"
    valuetype          = "INT64"
    dataBase           = "postgresql"
  }
  postgresql_tuples_processed_count = {
    type               = "delta"
    description        = <<-EOF
                    Number of tuplesrows processed for a given database for operations like  insert, update or delete.
                EOF
    launchStage        = "BETA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "postgresql"
    google_metric_path = "cloudsql.googleapis.com/database/postgresql/tuples_processed_count"
    label              = "Number of rows processed"
    unit               = "1"
    metricBin          = "['database']"
    valuetype          = "INT64"
    dataBase           = "postgresql"
  }
  oldest_transaction_age = {
    type               = "gauge"
    description        = <<-EOF
                    Age of the oldest transaction yet to be vacuumed in the Cloud SQL PostgreSQL instance, measured in number of transactions that have happened since the oldest transaction.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "cloudsql.googleapis.com/database/postgresql/vacuum/oldest_transaction_age"
    label              = "Oldest transaction age"
    unit               = "1"
    metricBin          = "['']"
    valuetype          = "INT64"
    dataBase           = "postgresql"
  }
  replication_log_archive_failure_count = {
    type               = "delta"
    description        = <<-EOF
                    Number of failed attempts for archiving replication log files.
                EOF
    launchStage        = "BETA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "replication"
    google_metric_path = "cloudsql.googleapis.com/database/replication/log_archive_failure_count"
    label              = "Number of log archival failures."
    unit               = "1"
    metricBin          = "['database']"
    valuetype          = "INT64"
    dataBase           = "ALL"
  }
  replication_log_archive_success_count = {
    type               = "delta"
    description        = <<-EOF
                    Number of successful attempts for archiving replication log files.
                EOF
    launchStage        = "BETA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "replication"
    google_metric_path = "cloudsql.googleapis.com/database/replication/log_archive_success_count"
    label              = "Number of log archival successes."
    unit               = "1"
    metricBin          = "['database']"
    valuetype          = "INT64"
    dataBase           = "ALL"
  }
  replication_network_lag = {
    type               = "gauge"
    description        = <<-EOF
                    Indicates time taken from primary binary log to IO thread on replica. Only applicable to replicas.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "replication"
    google_metric_path = "cloudsql.googleapis.com/database/replication/network_lag"
    label              = "Network lag"
    unit               = "s"
    metricBin          = "['database']"
    valuetype          = "INT64"
    dataBase           = "ALL"
  }
  replication_replica_lag = {
    type               = "gauge"
    description        = <<-EOF
                    Number of seconds the read replica is behind its primary approximation.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "replication"
    google_metric_path = "cloudsql.googleapis.com/database/replication/replica_lag"
    label              = "Replication lag"
    unit               = "s"
    metricBin          = "['database']"
    valuetype          = "DOUBLE"
    dataBase           = "ALL"
  }
  replication_state = {
    type               = "gauge"
    description        = <<-EOF
                    The current serving state of replication.
                EOF
    launchStage        = "BETA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "replication"
    google_metric_path = "cloudsql.googleapis.com/database/replication/state"
    label              = "Replication state"
    unit               = ""
    metricBin          = "['database']"
    valuetype          = "BOOL"
    dataBase           = "ALL"
  }
  sqlserver_audits_size = {
    type               = "gauge"
    description        = <<-EOF
                    Tracks the size in bytes of stored SQLServer audit files on an instance.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "sqlserver"
    google_metric_path = "cloudsql.googleapis.com/database/sqlserver/audits_size"
    label              = "Size of stored audit files."
    unit               = "By"
    metricBin          = "['database']"
    valuetype          = "INT64"
    dataBase           = "sqlserver"
  }
  sqlserver_audits_upload_count = {
    type               = "delta"
    description        = <<-EOF
                    Counts total number of SQLServer audit file uploads to a GCS bucket and whether or not an upload was successful.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "sqlserver"
    google_metric_path = "cloudsql.googleapis.com/database/sqlserver/audits_upload_count"
    label              = "Total number of successfully uploaded audits."
    unit               = "1"
    metricBin          = "['database']"
    valuetype          = "INT64"
    dataBase           = "sqlserver"
  }
  primary_to_replica_connection_health = {
    type               = "gauge"
    description        = <<-EOF
                    Indicates whether there is connectivity from Primary to the Replica to push replication updates.
                EOF
    launchStage        = "ALPHA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "cloudsql.googleapis.com/database/sqlserver/external_sync/primary_to_replica_connection_health"
    label              = "Primary to Replica connectivity"
    unit               = ""
    metricBin          = "['']"
    valuetype          = "BOOL"
    dataBase           = "sqlserver"
  }
  state = {
    type               = "gauge"
    description        = <<-EOF
                    The current serving state of the Cloud SQL instance. This can be one of the following:
RUNNING:  The instance is *expected* to be running. If an instance experiences unplanned non-maintenance downtime, the state will still be RUNNING, but the database/up metric will report 0.
SUSPENDED: The instance is not available, for example due to problems with billing.
RUNNABLE: The instance has been stopped by owner. It is not currently running, but it's ready to be restarted.
PENDING_CREATE: The instance is being created.
MAINTENANCE: The instance is down for maintenance.
FAILED: The instance creation failed or an operation left the instance in an unknown bad state.
UNKNOWN_STATE: The state of the instance is unknown.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "cloudsql.googleapis.com/database/state"
    label              = "State"
    unit               = ""
    metricBin          = "['database']"
    valuetype          = "STRING"
    dataBase           = "ALL"
  }
  up = {
    type               = "gauge"
    description        = <<-EOF
                    Indicates if the server is up or not.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "cloudsql.googleapis.com/database/up"
    label              = "Server up"
    unit               = "1"
    metricBin          = "['database']"
    valuetype          = "INT64"
    dataBase           = "ALL"
  }
  uptime = {
    type               = "delta"
    description        = <<-EOF
                    Delta count of the time in seconds the instance has been running.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "cloudsql.googleapis.com/database/uptime"
    label              = "Uptime"
    unit               = "s"
    metricBin          = "['database']"
    valuetype          = "INT64"
    dataBase           = "ALL"
  }
} }