
######################
# This file is autogenerated
# run serviceUtilities.py in service directory to create this file
# serviceUtilities.py -h for list of commands and options
######################
locals { metrics_definitions = {
  num_in_flight = {
    type               = "gauge"
    description        = <<-EOF
                    In flight jobs.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "bigquery.googleapis.com/job/num_in_flight"
    label              = "Job count"
    unit               = "1"
    metricBin          = "job"
    valuetype          = "INT64"

  }
  biengine_fallback_count = {
    type               = "delta"
    description        = <<-EOF
                    The reasons that queries failed BI Engine execution.
                EOF
    launchStage        = "BETA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "bigquery.googleapis.com/query/biengine_fallback_count"
    label              = "BI Engine query fallback count"
    unit               = "1"
    metricBin          = "query"
    valuetype          = "INT64"

  }
  count = {
    type               = "gauge"
    description        = <<-EOF
                    In flight queries.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "bigquery.googleapis.com/query/count"
    label              = "Query count"
    unit               = "1"
    metricBin          = "query"
    valuetype          = "INT64"

  }
  execution_count = {
    type               = "delta"
    description        = <<-EOF
                    The number of queries executed.
                EOF
    launchStage        = "BETA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "bigquery.googleapis.com/query/execution_count"
    label              = "Query execution count"
    unit               = "1"
    metricBin          = "query"
    valuetype          = "INT64"

  }
  execution_times = {
    type               = "gauge"
    description        = <<-EOF
                    Distribution of execution times for queries that completed successfully within the last sampling interval. Incomplete and failed queries are not included.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "bigquery.googleapis.com/query/execution_times"
    label              = "Query execution times"
    unit               = "s"
    metricBin          = "query"
    valuetype          = "DISTRIBUTION"

  }
  scanned_bytes = {
    type               = "delta"
    description        = <<-EOF
                    Scanned bytes.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "bigquery.googleapis.com/query/scanned_bytes"
    label              = "Scanned bytes"
    unit               = "By"
    metricBin          = "query"
    valuetype          = "INT64"

  }
  scanned_bytes_billed = {
    type               = "delta"
    description        = <<-EOF
                    Scanned bytes billed.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "bigquery.googleapis.com/query/scanned_bytes_billed"
    label              = "Scanned bytes billed"
    unit               = "By"
    metricBin          = "query"
    valuetype          = "INT64"

  }
  statement_scanned_bytes = {
    type               = "delta"
    description        = <<-EOF
                    Scanned bytes broken down by statement type.
                EOF
    launchStage        = "BETA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "bigquery.googleapis.com/query/statement_scanned_bytes"
    label              = "Statement scanned bytes"
    unit               = "By"
    metricBin          = "query"
    valuetype          = "INT64"

  }
  statement_scanned_bytes_billed = {
    type               = "delta"
    description        = <<-EOF
                    Scanned bytes billed broken down by statement type.
                EOF
    launchStage        = "BETA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "bigquery.googleapis.com/query/statement_scanned_bytes_billed"
    label              = "Statement scanned bytes billed"
    unit               = "By"
    metricBin          = "query"
    valuetype          = "INT64"

  }
  allocated = {
    type               = "gauge"
    description        = <<-EOF
                    Number of BigQuery slots currently allocated for project. Slot allocation can be broken down based on reservation and job type.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "bigquery.googleapis.com/slots/allocated"
    label              = "Slots used by project, reservation, and job type"
    unit               = "1"
    metricBin          = "slots"
    valuetype          = "INT64"

  }
  allocated_for_project = {
    type               = "gauge"
    description        = <<-EOF
                    Number of BigQuery slots currently allocated for query jobs in the project.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "bigquery.googleapis.com/slots/allocated_for_project"
    label              = "Slots used by project"
    unit               = "1"
    metricBin          = "slots"
    valuetype          = "INT64"

  }
  allocated_for_project_and_job_type = {
    type               = "gauge"
    description        = <<-EOF
                    Number of BigQuery slots currently allocated for the project and job type.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "bigquery.googleapis.com/slots/allocated_for_project_and_job_type"
    label              = "Slots used by project and job type"
    unit               = "1"
    metricBin          = "slots"
    valuetype          = "INT64"

  }
  allocated_for_reservation = {
    type               = "gauge"
    description        = <<-EOF
                    Number of BigQuery slots currently allocated for project in the reservation.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "bigquery.googleapis.com/slots/allocated_for_reservation"
    label              = "Slots used by project in reservation"
    unit               = "1"
    metricBin          = "slots"
    valuetype          = "INT64"

  }
  assigned = {
    type               = "gauge"
    description        = <<-EOF
                    The number of slots assigned to the given project/organization.
                EOF
    launchStage        = "BAD_VAL-1"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "bigquery.googleapis.com/slots/assigned"
    label              = "Slots assigned"
    unit               = "1"
    metricBin          = "slots"
    valuetype          = "INT64"

  }
  capacity_committed = {
    type               = "gauge"
    description        = <<-EOF
                    The total slot capacity commitments purchased through this administrator project/organization.
                EOF
    launchStage        = "BAD_VAL-1"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "bigquery.googleapis.com/slots/capacity_committed"
    label              = "Slots capacity committed"
    unit               = "1"
    metricBin          = "slots"
    valuetype          = "INT64"

  }
  max_assigned = {
    type               = "gauge"
    description        = <<-EOF
                    The maximum number of slots assigned to the given project/organization.
                EOF
    launchStage        = "BAD_VAL-1"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "bigquery.googleapis.com/slots/max_assigned"
    label              = "Slots max assigned"
    unit               = "1"
    metricBin          = "slots"
    valuetype          = "INT64"

  }
  total_allocated_for_reservation = {
    type               = "gauge"
    description        = <<-EOF
                    Number of BigQuery slots currently allocated across projects in the reservation. Note that the metric data is only reported while at least one project has been assigned to the reservation and is consuming slots. As an alternative, consider querying reservations information from INFORMATION_SCHEMA https://cloud.google.com/bigquery/docs/information-schema-reservations, which does not have these limitations.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "bigquery.googleapis.com/slots/total_allocated_for_reservation"
    label              = "Slots used across projects in reservation"
    unit               = "1"
    metricBin          = "slots"
    valuetype          = "INT64"

  }
  total_available = {
    type               = "gauge"
    description        = <<-EOF
                    Deprecated Total number of BigQuery slots available for the project. If you are using the BigQuery Reservations API, consider using bigquery.googleapis.com/slots/assigned and bigquery.googleapis.com/slots/max_assigned instead.
                EOF
    launchStage        = "BAD_VAL-5"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "bigquery.googleapis.com/slots/total_available"
    label              = "Total slots"
    unit               = "1"
    metricBin          = "slots"
    valuetype          = "INT64"

  }
  insertall_inserted_bytes = {
    type               = "delta"
    description        = <<-EOF
                    The number of bytes uploaded by the project using the InsertAll streaming API.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "bigquery.googleapis.com/storage/insertall_inserted_bytes"
    label              = "InsertAll Inserted Bytes"
    unit               = "1"
    metricBin          = "storage"
    valuetype          = "DOUBLE"

  }
  insertall_inserted_rows = {
    type               = "delta"
    description        = <<-EOF
                    The number of rows uploaded by the project using the InsertAll streaming API.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "bigquery.googleapis.com/storage/insertall_inserted_rows"
    label              = "InsertAll Inserted Rows"
    unit               = "1"
    metricBin          = "storage"
    valuetype          = "DOUBLE"

  }
  stored_bytes = {
    type               = "gauge"
    description        = <<-EOF
                    Number of bytes stored. The top 100 tables in a dataset are labeled, while the rest are grouped with no table label.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "bigquery.googleapis.com/storage/stored_bytes"
    label              = "Stored bytes"
    unit               = "By"
    metricBin          = "storage"
    valuetype          = "INT64"

  }
  table_count = {
    type               = "gauge"
    description        = <<-EOF
                    Number of tables.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "bigquery.googleapis.com/storage/table_count"
    label              = "Table count"
    unit               = "1"
    metricBin          = "storage"
    valuetype          = "INT64"

  }
  uploaded_bytes = {
    type               = "delta"
    description        = <<-EOF
                    Uploaded bytes.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "bigquery.googleapis.com/storage/uploaded_bytes"
    label              = "Uploaded bytes"
    unit               = "By"
    metricBin          = "storage"
    valuetype          = "INT64"

  }
  uploaded_bytes_billed = {
    type               = "delta"
    description        = <<-EOF
                    Uploaded bytes billed.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "bigquery.googleapis.com/storage/uploaded_bytes_billed"
    label              = "Uploaded bytes billed"
    unit               = "By"
    metricBin          = "storage"
    valuetype          = "INT64"

  }
  uploaded_row_count = {
    type               = "delta"
    description        = <<-EOF
                    Uploaded rows.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "bigquery.googleapis.com/storage/uploaded_row_count"
    label              = "Uploaded rows"
    unit               = "1"
    metricBin          = "storage"
    valuetype          = "INT64"

  }
} }