
######################
# This file is autogenerated
# run serviceUtilities.py in service directory to create this file
# serviceUtilities.py -h for list of commands and options
######################
locals { metrics_definitions = {
  active_instances = {
    type               = "gauge"
    description        = <<-EOF
                    The number of active function instances.
                EOF
    launchStage        = "BETA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "cloudfunctions.googleapis.com/function/active_instances"
    label              = "Active instances"
    unit               = "1"
    metricBin          = "function"
    valuetype          = "INT64"

  }
  execution_count = {
    type               = "delta"
    description        = <<-EOF
                    Count of function executions broken down by status.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "cloudfunctions.googleapis.com/function/execution_count"
    label              = "Executions"
    unit               = "1"
    metricBin          = "function"
    valuetype          = "INT64"

  }
  execution_times = {
    type               = "delta"
    description        = <<-EOF
                    Distribution of functions execution times in nanoseconds.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "cloudfunctions.googleapis.com/function/execution_times"
    label              = "Execution times"
    unit               = "ns"
    metricBin          = "function"
    valuetype          = "DISTRIBUTION"

  }
  instance_count = {
    type               = "gauge"
    description        = <<-EOF
                    The number of function instances, broken down by state.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "cloudfunctions.googleapis.com/function/instance_count"
    label              = "Instance Count"
    unit               = "1"
    metricBin          = "function"
    valuetype          = "INT64"

  }
  network_egress = {
    type               = "delta"
    description        = <<-EOF
                    Outgoing network traffic of function, in bytes.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "cloudfunctions.googleapis.com/function/network_egress"
    label              = "Network egress"
    unit               = "By"
    metricBin          = "function"
    valuetype          = "INT64"

  }
  user_memory_bytes = {
    type               = "delta"
    description        = <<-EOF
                    Distribution of maximum function's memory usage during execution, in bytes.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "cloudfunctions.googleapis.com/function/user_memory_bytes"
    label              = "Memory usage"
    unit               = "By"
    metricBin          = "function"
    valuetype          = "DISTRIBUTION"

  }
} }