
######################
# This file is autogenerated
# run serviceUtilities.py in service directory to create this file
# serviceUtilities.py -h for list of commands and options
######################
locals { service_metrics_definitions = {
  request_count = {
    type               = "delta"
    description        = <<-EOF
                    The count of completed requests.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "serviceruntime.googleapis.com/api/request_count"
    label              = "Request count"
    unit               = "1"
    metricBin          = "api"
    valuetype          = "INT64"

  }
  request_latencies = {
    type               = "delta"
    description        = <<-EOF
                    Distribution of latencies in seconds for non-streaming requests.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "serviceruntime.googleapis.com/api/request_latencies"
    label              = "Request latencies"
    unit               = "s"
    metricBin          = "api"
    valuetype          = "DISTRIBUTION"

  }
  request_latencies_backend = {
    type               = "delta"
    description        = <<-EOF
                    Distribution of backend latencies in seconds for non-streaming requests.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "serviceruntime.googleapis.com/api/request_latencies_backend"
    label              = "Request backend latencies"
    unit               = "s"
    metricBin          = "api"
    valuetype          = "DISTRIBUTION"

  }
  request_latencies_overhead = {
    type               = "delta"
    description        = <<-EOF
                    Distribution of request latencies in seconds for non-streaming requests excluding the backend.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "serviceruntime.googleapis.com/api/request_latencies_overhead"
    label              = "Request overhead latencies"
    unit               = "s"
    metricBin          = "api"
    valuetype          = "DISTRIBUTION"

  }
  request_sizes = {
    type               = "delta"
    description        = <<-EOF
                    Distribution of request sizes in bytes recorded at request completion.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "serviceruntime.googleapis.com/api/request_sizes"
    label              = "Request sizes"
    unit               = "By"
    metricBin          = "api"
    valuetype          = "DISTRIBUTION"

  }
  response_sizes = {
    type               = "delta"
    description        = <<-EOF
                    Distribution of response sizes in bytes recorded at request completion.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "serviceruntime.googleapis.com/api/response_sizes"
    label              = "Response sizes"
    unit               = "By"
    metricBin          = "api"
    valuetype          = "DISTRIBUTION"

  }
  allocation_usage = {
    type               = "gauge"
    description        = <<-EOF
                    The total consumed allocation quota. Values reported more than 1/min are dropped. If no changes are received in quota usage, the last value is repeated at least every 24 hours.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "allocation"
    google_metric_path = "serviceruntime.googleapis.com/quota/allocation/usage"
    label              = "Allocation quota usage"
    unit               = "1"
    metricBin          = "quota"
    valuetype          = "INT64"

  }
  concurrent_exceeded = {
    type               = "delta"
    description        = <<-EOF
                    The number of times exceeding the quota was attempted.
                EOF
    launchStage        = "ALPHA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "concurrent"
    google_metric_path = "serviceruntime.googleapis.com/quota/concurrent/exceeded"
    label              = "Quota Exceeded"
    unit               = "1"
    metricBin          = "quota"
    valuetype          = "INT64"

  }
  concurrent_limit = {
    type               = "gauge"
    description        = <<-EOF
                    The limit for the quota.
                EOF
    launchStage        = "ALPHA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "concurrent"
    google_metric_path = "serviceruntime.googleapis.com/quota/concurrent/limit"
    label              = "Quota limit"
    unit               = "1"
    metricBin          = "quota"
    valuetype          = "INT64"

  }
  concurrent_usage = {
    type               = "gauge"
    description        = <<-EOF
                    The concurrent usage of the quota.
                EOF
    launchStage        = "ALPHA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "concurrent"
    google_metric_path = "serviceruntime.googleapis.com/quota/concurrent/usage"
    label              = "Quota usage"
    unit               = "1"
    metricBin          = "quota"
    valuetype          = "INT64"

  }
  exceeded = {
    type               = "gauge"
    description        = <<-EOF
                    The error happened when the quota limit was exceeded.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "serviceruntime.googleapis.com/quota/exceeded"
    label              = "Quota exceeded error"
    unit               = "1"
    metricBin          = "quota"
    valuetype          = "BOOL"

  }
  limit = {
    type               = "gauge"
    description        = <<-EOF
                    The limit for the quota.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "serviceruntime.googleapis.com/quota/limit"
    label              = "Quota limit"
    unit               = "1"
    metricBin          = "quota"
    valuetype          = "INT64"

  }
  rate_net_usage = {
    type               = "delta"
    description        = <<-EOF
                    The total consumed rate quota.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "rate"
    google_metric_path = "serviceruntime.googleapis.com/quota/rate/net_usage"
    label              = "Rate quota usage"
    unit               = "1"
    metricBin          = "quota"
    valuetype          = "INT64"

  }
  metric1 = {
    type               = "delta"
    description        = <<-EOF
                    Deprecated.
                EOF
    launchStage        = "BAD_VAL-1"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "serviceruntime.googleapis.com/reserved/metric1"
    label              = "Deprecated"
    unit               = "1"
    metricBin          = "reserved"
    valuetype          = "INT64"

  }
} }