
######################
# This file is autogenerated
# run serviceUtilities.py in service directory to create this file
# serviceUtilities.py -h for list of commands and options
######################
locals { metrics_definitions = {
  backlog_bytes = {
    type               = "gauge"
    description        = <<-EOF
                    Total byte size of the messages retained in a snapshot.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "pubsub.googleapis.com/snapshot/backlog_bytes"
    label              = "Snapshot backlog bytes"
    unit               = "By"
    metricBin          = "snapshot"
    valuetype          = "INT64"

  }
  backlog_bytes_by_region = {
    type               = "gauge"
    description        = <<-EOF
                    Total byte size of the messages retained in a snapshot, broken down by Cloud region.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "pubsub.googleapis.com/snapshot/backlog_bytes_by_region"
    label              = "Snapshot backlog bytes by region"
    unit               = "By"
    metricBin          = "snapshot"
    valuetype          = "INT64"

  }
  config_updates_count = {
    type               = "delta"
    description        = <<-EOF
                    Cumulative count of configuration changes, grouped by operation type and result.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "pubsub.googleapis.com/snapshot/config_updates_count"
    label              = "Snapshot updates"
    unit               = "1"
    metricBin          = "snapshot"
    valuetype          = "INT64"

  }
  num_messages = {
    type               = "gauge"
    description        = <<-EOF
                    Number of messages retained in a snapshot.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "pubsub.googleapis.com/snapshot/num_messages"
    label              = "Snapshot messages"
    unit               = "1"
    metricBin          = "snapshot"
    valuetype          = "INT64"

  }
  num_messages_by_region = {
    type               = "gauge"
    description        = <<-EOF
                    Number of messages retained in a snapshot, broken down by Cloud region.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "pubsub.googleapis.com/snapshot/num_messages_by_region"
    label              = "Snapshot messages by region"
    unit               = "1"
    metricBin          = "snapshot"
    valuetype          = "INT64"

  }
  oldest_message_age = {
    type               = "gauge"
    description        = <<-EOF
                    Age in seconds of the oldest message retained in a snapshot.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "pubsub.googleapis.com/snapshot/oldest_message_age"
    label              = "Oldest snapshot message age"
    unit               = "s"
    metricBin          = "snapshot"
    valuetype          = "INT64"

  }
  oldest_message_age_by_region = {
    type               = "gauge"
    description        = <<-EOF
                    Age in seconds of the oldest message retained in a snapshot, broken down by Cloud region.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "pubsub.googleapis.com/snapshot/oldest_message_age_by_region"
    label              = "Oldest snapshot message age by region"
    unit               = "s"
    metricBin          = "snapshot"
    valuetype          = "INT64"

  }
  ack_latencies = {
    type               = "delta"
    description        = <<-EOF
                    Distribution of ack latencies in milliseconds. The ack latency is the time between when Cloud Pub/Sub sends a message to a subscriber client and when Cloud Pub/Sub receives an Acknowledge request for that message.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "pubsub.googleapis.com/subscription/ack_latencies"
    label              = "Ack latency"
    unit               = "ms"
    metricBin          = "subscription"
    valuetype          = "DISTRIBUTION"

  }
  ack_message_count = {
    type               = "delta"
    description        = <<-EOF
                    Cumulative count of messages acknowledged by Acknowledge requests, grouped by delivery type.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "pubsub.googleapis.com/subscription/ack_message_count"
    label              = "Ack message count"
    unit               = "1"
    metricBin          = "subscription"
    valuetype          = "INT64"

  }
  backlog_bytes = {
    type               = "gauge"
    description        = <<-EOF
                    Total byte size of the unacknowledged messages a.k.a. backlog messages in a subscription.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "pubsub.googleapis.com/subscription/backlog_bytes"
    label              = "Backlog size"
    unit               = "By"
    metricBin          = "subscription"
    valuetype          = "INT64"

  }
  byte_cost = {
    type               = "delta"
    description        = <<-EOF
                    Cumulative cost of operations, measured in bytes. This is used to measure quota utilization.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "pubsub.googleapis.com/subscription/byte_cost"
    label              = "Subscription byte cost"
    unit               = "By"
    metricBin          = "subscription"
    valuetype          = "INT64"

  }
  config_updates_count = {
    type               = "delta"
    description        = <<-EOF
                    Cumulative count of configuration changes for each subscription, grouped by operation type and result.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "pubsub.googleapis.com/subscription/config_updates_count"
    label              = "Subscription updates"
    unit               = "1"
    metricBin          = "subscription"
    valuetype          = "INT64"

  }
  dead_letter_message_count = {
    type               = "delta"
    description        = <<-EOF
                    Cumulative count of messages published to dead letter topic, grouped by result.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "pubsub.googleapis.com/subscription/dead_letter_message_count"
    label              = "Dead letter message count"
    unit               = "1"
    metricBin          = "subscription"
    valuetype          = "INT64"

  }
  delivery_latency_health_score = {
    type               = "gauge"
    description        = <<-EOF
                    A score that measures the health of a subscription over a 10 minute rolling window.
                EOF
    launchStage        = "BETA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "pubsub.googleapis.com/subscription/delivery_latency_health_score"
    label              = "Delivery latency health score"
    unit               = "1"
    metricBin          = "subscription"
    valuetype          = "BOOL"

  }
  exactly_once_warning_count = {
    type               = "delta"
    description        = <<-EOF
                    Count of instances acks and modacks that may have failed that may lead to message redeliveries.
                EOF
    launchStage        = "BETA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "pubsub.googleapis.com/subscription/exactly_once_warning_count"
    label              = "Exactly once delivery warning"
    unit               = "1"
    metricBin          = "subscription"
    valuetype          = "INT64"

  }
  expired_ack_deadlines_count = {
    type               = "delta"
    description        = <<-EOF
                    Cumulative count of messages whose ack deadline expired while the message was outstanding to a subscriber client.
                EOF
    launchStage        = "BETA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "pubsub.googleapis.com/subscription/expired_ack_deadlines_count"
    label              = "Expired ack deadlines count"
    unit               = "1"
    metricBin          = "subscription"
    valuetype          = "INT64"

  }
  mod_ack_deadline_message_count = {
    type               = "delta"
    description        = <<-EOF
                    Cumulative count of messages whose deadline was updated by ModifyAckDeadline requests, grouped by delivery type.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "pubsub.googleapis.com/subscription/mod_ack_deadline_message_count"
    label              = "Mod ack deadline message count"
    unit               = "1"
    metricBin          = "subscription"
    valuetype          = "INT64"

  }
  mod_ack_deadline_message_operation_count = {
    type               = "delta"
    description        = <<-EOF
                    Cumulative count of ModifyAckDeadline message operations, grouped by result. This metric is deprecated. Use subscription/mod_ack_deadline_request_count instead.
                EOF
    launchStage        = "BAD_VAL-5"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "pubsub.googleapis.com/subscription/mod_ack_deadline_message_operation_count"
    label              = "ModifyAckDeadline message operations"
    unit               = "1"
    metricBin          = "subscription"
    valuetype          = "INT64"

  }
  mod_ack_deadline_request_count = {
    type               = "delta"
    description        = <<-EOF
                    Cumulative count of ModifyAckDeadline requests, grouped by result.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "pubsub.googleapis.com/subscription/mod_ack_deadline_request_count"
    label              = "ModifyAckDeadline requests"
    unit               = "1"
    metricBin          = "subscription"
    valuetype          = "INT64"

  }
  num_outstanding_messages = {
    type               = "gauge"
    description        = <<-EOF
                    Number of messages delivered to a subscription's push endpoint, but not yet acknowledged.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "pubsub.googleapis.com/subscription/num_outstanding_messages"
    label              = "Outstanding push messages"
    unit               = "1"
    metricBin          = "subscription"
    valuetype          = "INT64"

  }
  num_retained_acked_messages = {
    type               = "gauge"
    description        = <<-EOF
                    Number of acknowledged messages retained in a subscription.
                EOF
    launchStage        = "ALPHA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "pubsub.googleapis.com/subscription/num_retained_acked_messages"
    label              = "Retained acked messages"
    unit               = "1"
    metricBin          = "subscription"
    valuetype          = "INT64"

  }
  num_retained_acked_messages_by_region = {
    type               = "gauge"
    description        = <<-EOF
                    Number of acknowledged messages retained in a subscription, broken down by Cloud region.
                EOF
    launchStage        = "BETA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "pubsub.googleapis.com/subscription/num_retained_acked_messages_by_region"
    label              = "Retained acked messages by region"
    unit               = "1"
    metricBin          = "subscription"
    valuetype          = "INT64"

  }
  num_unacked_messages_by_region = {
    type               = "gauge"
    description        = <<-EOF
                    Number of unacknowledged messages in a subscription, broken down by Cloud region.
                EOF
    launchStage        = "BETA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "pubsub.googleapis.com/subscription/num_unacked_messages_by_region"
    label              = "Unacked messages by region"
    unit               = "1"
    metricBin          = "subscription"
    valuetype          = "INT64"

  }
  num_undelivered_messages = {
    type               = "gauge"
    description        = <<-EOF
                    Number of unacknowledged messages a.k.a. backlog messages in a subscription.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "pubsub.googleapis.com/subscription/num_undelivered_messages"
    label              = "Unacked messages"
    unit               = "1"
    metricBin          = "subscription"
    valuetype          = "INT64"

  }
  oldest_retained_acked_message_age = {
    type               = "gauge"
    description        = <<-EOF
                    Age in seconds of the oldest acknowledged message retained in a subscription.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "pubsub.googleapis.com/subscription/oldest_retained_acked_message_age"
    label              = "Oldest retained acked message age"
    unit               = "s"
    metricBin          = "subscription"
    valuetype          = "INT64"

  }
  oldest_retained_acked_message_age_by_region = {
    type               = "gauge"
    description        = <<-EOF
                    Age in seconds of the oldest acknowledged message retained in a subscription, broken down by Cloud region.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "pubsub.googleapis.com/subscription/oldest_retained_acked_message_age_by_region"
    label              = "Oldest retained acked message age by region"
    unit               = "s"
    metricBin          = "subscription"
    valuetype          = "INT64"

  }
  oldest_unacked_message_age = {
    type               = "gauge"
    description        = <<-EOF
                    Age in seconds of the oldest unacknowledged message a.k.a. backlog message in a subscription.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "pubsub.googleapis.com/subscription/oldest_unacked_message_age"
    label              = "Oldest unacked message age"
    unit               = "s"
    metricBin          = "subscription"
    valuetype          = "INT64"

  }
  oldest_unacked_message_age_by_region = {
    type               = "gauge"
    description        = <<-EOF
                    Age in seconds of the oldest unacknowledged message in a subscription, broken down by Cloud region.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "pubsub.googleapis.com/subscription/oldest_unacked_message_age_by_region"
    label              = "Oldest unacked message age by region"
    unit               = "s"
    metricBin          = "subscription"
    valuetype          = "INT64"

  }
  open_streaming_pulls = {
    type               = "gauge"
    description        = <<-EOF
                    Number of open StreamingPull streams per subscription, grouped by status.
                EOF
    launchStage        = "BETA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "pubsub.googleapis.com/subscription/open_streaming_pulls"
    label              = "Number of open streaming pulls"
    unit               = "1"
    metricBin          = "subscription"
    valuetype          = "INT64"

  }
  pull_ack_message_operation_count = {
    type               = "delta"
    description        = <<-EOF
                    Cumulative count of acknowledge message operations, grouped by result. This metric is deprecated. Use subscription/pull_ack_request_count instead.
                EOF
    launchStage        = "BAD_VAL-5"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "pubsub.googleapis.com/subscription/pull_ack_message_operation_count"
    label              = "Acknowledge message operations"
    unit               = "1"
    metricBin          = "subscription"
    valuetype          = "INT64"

  }
  pull_ack_request_count = {
    type               = "delta"
    description        = <<-EOF
                    Cumulative count of acknowledge requests, grouped by result.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "pubsub.googleapis.com/subscription/pull_ack_request_count"
    label              = "Acknowledge requests"
    unit               = "1"
    metricBin          = "subscription"
    valuetype          = "INT64"

  }
  pull_message_operation_count = {
    type               = "delta"
    description        = <<-EOF
                    Cumulative count of pull message operations, grouped by result. This metric is deprecated. Use subscription/pull_request_count instead.
                EOF
    launchStage        = "BAD_VAL-5"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "pubsub.googleapis.com/subscription/pull_message_operation_count"
    label              = "Pull operations"
    unit               = "1"
    metricBin          = "subscription"
    valuetype          = "INT64"

  }
  pull_request_count = {
    type               = "delta"
    description        = <<-EOF
                    Cumulative count of pull requests, grouped by result.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "pubsub.googleapis.com/subscription/pull_request_count"
    label              = "Pull requests"
    unit               = "1"
    metricBin          = "subscription"
    valuetype          = "INT64"

  }
  push_request_count = {
    type               = "delta"
    description        = <<-EOF
                    Cumulative count of push attempts, grouped by result. Unlike pulls, the push server implementation does not batch user messages. So each request only contains one user message. The push server retries on errors, so a given user message can appear multiple times.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "pubsub.googleapis.com/subscription/push_request_count"
    label              = "Push requests"
    unit               = "1"
    metricBin          = "subscription"
    valuetype          = "INT64"

  }
  push_request_latencies = {
    type               = "delta"
    description        = <<-EOF
                    Distribution of push request latencies in microseconds, grouped by result.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "pubsub.googleapis.com/subscription/push_request_latencies"
    label              = "Push latency"
    unit               = "us"
    metricBin          = "subscription"
    valuetype          = "DISTRIBUTION"

  }
  retained_acked_bytes = {
    type               = "gauge"
    description        = <<-EOF
                    Total byte size of the acknowledged messages retained in a subscription.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "pubsub.googleapis.com/subscription/retained_acked_bytes"
    label              = "Retained acked bytes"
    unit               = "By"
    metricBin          = "subscription"
    valuetype          = "INT64"

  }
  retained_acked_bytes_by_region = {
    type               = "gauge"
    description        = <<-EOF
                    Total byte size of the acknowledged messages retained in a subscription, broken down by Cloud region.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "pubsub.googleapis.com/subscription/retained_acked_bytes_by_region"
    label              = "Retained acked bytes by region"
    unit               = "By"
    metricBin          = "subscription"
    valuetype          = "INT64"

  }
  seek_request_count = {
    type               = "delta"
    description        = <<-EOF
                    Cumulative count of seek attempts, grouped by result.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "pubsub.googleapis.com/subscription/seek_request_count"
    label              = "Seek requests"
    unit               = "1"
    metricBin          = "subscription"
    valuetype          = "INT64"

  }
  sent_message_count = {
    type               = "delta"
    description        = <<-EOF
                    Cumulative count of messages sent by Cloud Pub/Sub to subscriber clients, grouped by delivery type.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "pubsub.googleapis.com/subscription/sent_message_count"
    label              = "Sent message count"
    unit               = "1"
    metricBin          = "subscription"
    valuetype          = "INT64"

  }
  streaming_pull_ack_message_operation_count = {
    type               = "delta"
    description        = <<-EOF
                    Cumulative count of StreamingPull acknowledge message operations, grouped by result. This metric is deprecated. Use subscription/streaming_pull_ack_request_count instead.
                EOF
    launchStage        = "BAD_VAL-5"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "pubsub.googleapis.com/subscription/streaming_pull_ack_message_operation_count"
    label              = "StreamingPull Acknowledge message operations"
    unit               = "1"
    metricBin          = "subscription"
    valuetype          = "INT64"

  }
  streaming_pull_ack_request_count = {
    type               = "delta"
    description        = <<-EOF
                    Cumulative count of streaming pull requests with non-empty acknowledge ids, grouped by result.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "pubsub.googleapis.com/subscription/streaming_pull_ack_request_count"
    label              = "StreamingPull Acknowledge requests"
    unit               = "1"
    metricBin          = "subscription"
    valuetype          = "INT64"

  }
  streaming_pull_message_operation_count = {
    type               = "delta"
    description        = <<-EOF
                    Cumulative count of streaming pull message operations, grouped by result. This metric is deprecated. Use subscription/streaming_pull_response_count instead.
                EOF
    launchStage        = "BAD_VAL-5"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "pubsub.googleapis.com/subscription/streaming_pull_message_operation_count"
    label              = "StreamingPull message operations"
    unit               = "1"
    metricBin          = "subscription"
    valuetype          = "INT64"

  }
  streaming_pull_mod_ack_deadline_message_operation_count = {
    type               = "delta"
    description        = <<-EOF
                    Cumulative count of StreamingPull ModifyAckDeadline operations, grouped by result. This metric is deprecated. Use subscription/streaming_pull_mod_ack_deadline_request_count instead.
                EOF
    launchStage        = "BAD_VAL-5"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "pubsub.googleapis.com/subscription/streaming_pull_mod_ack_deadline_message_operation_count"
    label              = "StreamingPull ModifyAckDeadline message operations"
    unit               = "1"
    metricBin          = "subscription"
    valuetype          = "INT64"

  }
  streaming_pull_mod_ack_deadline_request_count = {
    type               = "delta"
    description        = <<-EOF
                    Cumulative count of streaming pull requests with non-empty ModifyAckDeadline fields, grouped by result.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "pubsub.googleapis.com/subscription/streaming_pull_mod_ack_deadline_request_count"
    label              = "StreamingPull ModifyAckDeadline requests"
    unit               = "1"
    metricBin          = "subscription"
    valuetype          = "INT64"

  }
  streaming_pull_response_count = {
    type               = "delta"
    description        = <<-EOF
                    Cumulative count of streaming pull responses, grouped by result.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "pubsub.googleapis.com/subscription/streaming_pull_response_count"
    label              = "StreamingPull responses"
    unit               = "1"
    metricBin          = "subscription"
    valuetype          = "INT64"

  }
  unacked_bytes_by_region = {
    type               = "gauge"
    description        = <<-EOF
                    Total byte size of the unacknowledged messages in a subscription, broken down by Cloud region.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "pubsub.googleapis.com/subscription/unacked_bytes_by_region"
    label              = "Unacked bytes by region"
    unit               = "By"
    metricBin          = "subscription"
    valuetype          = "INT64"

  }
  byte_cost = {
    type               = "delta"
    description        = <<-EOF
                    Cost of operations, measured in bytes. This is used to measure utilization for quotas.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "pubsub.googleapis.com/topic/byte_cost"
    label              = "Topic byte cost"
    unit               = "By"
    metricBin          = "topic"
    valuetype          = "INT64"

  }
  config_updates_count = {
    type               = "delta"
    description        = <<-EOF
                    Cumulative count of configuration changes, grouped by operation type and result.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "pubsub.googleapis.com/topic/config_updates_count"
    label              = "Topic updates"
    unit               = "1"
    metricBin          = "topic"
    valuetype          = "INT64"

  }
  message_sizes = {
    type               = "delta"
    description        = <<-EOF
                    Distribution of publish message sizes in bytes.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "pubsub.googleapis.com/topic/message_sizes"
    label              = "Publish message size"
    unit               = "By"
    metricBin          = "topic"
    valuetype          = "DISTRIBUTION"

  }
  num_retained_acked_messages_by_region = {
    type               = "gauge"
    description        = <<-EOF
                    Number of acknowledged messages retained in a topic, broken down by Cloud region.
                EOF
    launchStage        = "BETA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "pubsub.googleapis.com/topic/num_retained_acked_messages_by_region"
    label              = "Retained acked messages by region"
    unit               = "1"
    metricBin          = "topic"
    valuetype          = "INT64"

  }
  num_retained_messages = {
    type               = "gauge"
    description        = <<-EOF
                    Number of messages retained in a topic.
                EOF
    launchStage        = "BETA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "pubsub.googleapis.com/topic/num_retained_messages"
    label              = "Retained messages"
    unit               = "1"
    metricBin          = "topic"
    valuetype          = "INT64"

  }
  num_unacked_messages_by_region = {
    type               = "gauge"
    description        = <<-EOF
                    Number of unacknowledged messages in a topic, broken down by Cloud region.
                EOF
    launchStage        = "BETA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "pubsub.googleapis.com/topic/num_unacked_messages_by_region"
    label              = "Unacked messages by region"
    unit               = "1"
    metricBin          = "topic"
    valuetype          = "INT64"

  }
  oldest_retained_acked_message_age_by_region = {
    type               = "gauge"
    description        = <<-EOF
                    Age in seconds of the oldest acknowledged message retained in a topic, broken down by Cloud region.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "pubsub.googleapis.com/topic/oldest_retained_acked_message_age_by_region"
    label              = "Oldest retained acked message age by region"
    unit               = "s"
    metricBin          = "topic"
    valuetype          = "INT64"

  }
  oldest_retained_message_age = {
    type               = "gauge"
    description        = <<-EOF
                    Age in seconds of the oldest message retained in a topic.
                EOF
    launchStage        = "BETA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "pubsub.googleapis.com/topic/oldest_retained_message_age"
    label              = "Oldest retained message age"
    unit               = "s"
    metricBin          = "topic"
    valuetype          = "INT64"

  }
  oldest_unacked_message_age_by_region = {
    type               = "gauge"
    description        = <<-EOF
                    Age in seconds of the oldest unacknowledged message in a topic, broken down by Cloud region.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "pubsub.googleapis.com/topic/oldest_unacked_message_age_by_region"
    label              = "Oldest unacked message age by region"
    unit               = "s"
    metricBin          = "topic"
    valuetype          = "INT64"

  }
  retained_acked_bytes_by_region = {
    type               = "gauge"
    description        = <<-EOF
                    Total byte size of the acknowledged messages retained in a topic, broken down by Cloud region.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "pubsub.googleapis.com/topic/retained_acked_bytes_by_region"
    label              = "Retained acked bytes by region"
    unit               = "By"
    metricBin          = "topic"
    valuetype          = "INT64"

  }
  retained_bytes = {
    type               = "gauge"
    description        = <<-EOF
                    Total byte size of the messages retained in a topic.
                EOF
    launchStage        = "BETA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "pubsub.googleapis.com/topic/retained_bytes"
    label              = "Retained bytes"
    unit               = "By"
    metricBin          = "topic"
    valuetype          = "INT64"

  }
  send_message_operation_count = {
    type               = "delta"
    description        = <<-EOF
                    Cumulative count of publish message operations, grouped by result. This metric is deprecated. Apply a count aggregator on topic/message_sizes instead.
                EOF
    launchStage        = "BAD_VAL-5"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "pubsub.googleapis.com/topic/send_message_operation_count"
    label              = "Publish message operations"
    unit               = "1"
    metricBin          = "topic"
    valuetype          = "INT64"

  }
  send_request_count = {
    type               = "delta"
    description        = <<-EOF
                    Cumulative count of publish requests, grouped by result.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "pubsub.googleapis.com/topic/send_request_count"
    label              = "Publish requests"
    unit               = "1"
    metricBin          = "topic"
    valuetype          = "INT64"

  }
  send_request_latencies = {
    type               = "delta"
    description        = <<-EOF
                    Distribution of publish request latencies in microseconds.
                EOF
    launchStage        = "BETA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "pubsub.googleapis.com/topic/send_request_latencies"
    label              = "Publish request latency"
    unit               = "us"
    metricBin          = "topic"
    valuetype          = "DISTRIBUTION"

  }
  unacked_bytes_by_region = {
    type               = "gauge"
    description        = <<-EOF
                    Total byte size of the unacknowledged messages in a topic, broken down by Cloud region.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "pubsub.googleapis.com/topic/unacked_bytes_by_region"
    label              = "Unacked bytes by region"
    unit               = "By"
    metricBin          = "topic"
    valuetype          = "INT64"

  }
} }