locals {
  cloud_run_service_instances = resource.observe_dataset.cloud_run_service_instances.id
  #cloud_functions_metrics   = resource.observe_dataset.cloud_functions_metrics[0].id
  #cloud_functions_logs      = resource.observe_dataset.cloud_functions_function_logs.id
  #dashboard_name            = format(var.name_format, "Monitoring")

  freshness = merge({}, var.freshness_overrides)
  workspace = var.workspace.oid

  /*

  workspace = local.datasets.REPLACE_WITH_DATASET_NAME.workspace
  name        = local.datasets.REPLACE_WITH_DATASET_NAME.name
  freshness   = local.datasets.REPLACE_WITH_DATASET_NAME.freshness
  description = local.datasets.REPLACE_WITH_DATASET_NAME.description

*/

  datasets = {
    cloud_run_service_instances = {
      workspace   = local.workspace
      name        = format(var.name_format, "Service Instances")
      freshness   = lookup(local.freshness, "cloud_run_service_instances", var.freshness_default_duration)
      description = "This dataset is used to create Cloud Run Service instances"
    }

    cloud_run_revision_instances = {
      workspace   = local.workspace
      name        = format(var.name_format, "Revision Instances")
      freshness   = lookup(local.freshness, "cloud_run_revision_instances", var.freshness_default_duration)
      description = "This dataset is used to create Cloud Run Revision instances"
    }

    cloud_run_metrics = {
      workspace   = local.workspace
      name        = format(var.name_format, "Metrics")
      freshness   = lookup(local.freshness, "cloud_run_metrics", var.freshness_default_duration)
      description = "This dataset contains metrics collected for Cloud Run"
    }

    cloud_run_service_logs = {
      workspace   = local.workspace
      name        = format(var.name_format, "Logs")
      freshness   = lookup(local.freshness, "cloud_run_service_logs", var.freshness_default_duration)
      description = "This dataset contains run logs generated by Cloud Run services"
    }

    cloud_run_audit_logs = {
      workspace   = local.workspace
      name        = format(var.name_format, "Audit Logs")
      freshness   = lookup(local.freshness, "cloud_run_audit_logs", var.freshness_default_duration)
      description = "This dataset contains audit logs generated by Cloud Run operations"
    }
  }
}
