
######################
# This file is autogenerated
# run serviceUtilities.py in service directory to create this file
# serviceUtilities.py -h for list of commands and options
######################
locals { metrics_definitions = {
  active_connections = {
    type               = "gauge"
    description        = <<-EOF
                    Connections active in this Memcached node.
                EOF
    launchStage        = "BETA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "memcache.googleapis.com/node/active_connections"
    label              = "Active connections"
    unit               = "1"
    metricBin          = "node"
    valuetype          = "INT64"

  }
  cache_memory = {
    type               = "gauge"
    description        = <<-EOF
                    Bytes alloted for the Memcached cache in this node, grouped by whether that memory is used or not.
                EOF
    launchStage        = "BETA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "memcache.googleapis.com/node/cache_memory"
    label              = "Cache memory usage"
    unit               = "By"
    metricBin          = "node"
    valuetype          = "INT64"

  }
  cpu_usage_time = {
    type               = "delta"
    description        = <<-EOF
                    CPU usage time by Memcached process grouped by user and kernel mode.
                EOF
    launchStage        = "BETA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "cpu"
    google_metric_path = "memcache.googleapis.com/node/cpu/usage_time"
    label              = "CPU usage time"
    unit               = "s{CPU}"
    metricBin          = "node"
    valuetype          = "DOUBLE"

  }
  cpu_utilization = {
    type               = "delta"
    description        = <<-EOF
                    CPU usage percent by Memcached node.
                EOF
    launchStage        = "BETA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "cpu"
    google_metric_path = "memcache.googleapis.com/node/cpu/utilization"
    label              = "CPU usage percent"
    unit               = "10^2.%"
    metricBin          = "node"
    valuetype          = "DOUBLE"

  }
  eviction_count = {
    type               = "delta"
    description        = <<-EOF
                    Count of items evicted by this Memcached node.
                EOF
    launchStage        = "BETA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "memcache.googleapis.com/node/eviction_count"
    label              = "Eviction count"
    unit               = "1"
    metricBin          = "node"
    valuetype          = "INT64"

  }
  hit_ratio = {
    type               = "gauge"
    description        = <<-EOF
                    Hit ratio, expressed as a percentage of the total cache requests excluding set operations. Values are numbers between 0.0 and 1.0, charts display the values as a percentage between 0% and 100%.
                EOF
    launchStage        = "BETA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "memcache.googleapis.com/node/hit_ratio"
    label              = "Hit ratio"
    unit               = "10^2.%"
    metricBin          = "node"
    valuetype          = "DOUBLE"

  }
  items = {
    type               = "gauge"
    description        = <<-EOF
                    Items stored in this Memcached node.
                EOF
    launchStage        = "BETA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "memcache.googleapis.com/node/items"
    label              = "Items"
    unit               = "1"
    metricBin          = "node"
    valuetype          = "INT64"

  }
  memory_utilization = {
    type               = "gauge"
    description        = <<-EOF
                    Utilization of system memory by Memcached node.
                EOF
    launchStage        = "BETA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "memory"
    google_metric_path = "memcache.googleapis.com/node/memory/utilization"
    label              = "System memory utilization"
    unit               = "10^2.%"
    metricBin          = "node"
    valuetype          = "DOUBLE"

  }
  operation_count = {
    type               = "delta"
    description        = <<-EOF
                    Count of Memcached operations grouped by command and response_type e.g. hit, miss.
                EOF
    launchStage        = "BETA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "memcache.googleapis.com/node/operation_count"
    label              = "Memcached operation count"
    unit               = "1"
    metricBin          = "node"
    valuetype          = "INT64"

  }
  received_bytes_count = {
    type               = "delta"
    description        = <<-EOF
                    Bytes received by this Memcached node.
                EOF
    launchStage        = "BETA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "memcache.googleapis.com/node/received_bytes_count"
    label              = "Received bytes"
    unit               = "By"
    metricBin          = "node"
    valuetype          = "INT64"

  }
  sent_bytes_count = {
    type               = "delta"
    description        = <<-EOF
                    Bytes sent by this Memcached node.
                EOF
    launchStage        = "BETA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "memcache.googleapis.com/node/sent_bytes_count"
    label              = "Sent bytes"
    unit               = "By"
    metricBin          = "node"
    valuetype          = "INT64"

  }
  uptime = {
    type               = "gauge"
    description        = <<-EOF
                    Time in seconds the node has been running.
                EOF
    launchStage        = "BETA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "memcache.googleapis.com/node/uptime"
    label              = "Uptime"
    unit               = "s"
    metricBin          = "node"
    valuetype          = "INT64"

  }
} }