
######################
# This file is autogenerated
# run serviceUtilities.py in service directory to create this file
# serviceUtilities.py -h for list of commands and options
######################
locals { metrics_definitions = {
  backend_latencies = {
    type               = "delta"
    description        = <<-EOF
                    A distribution of the latency calculated from when the request was sent by the proxy to the backend until the proxy received from the backend the last byte of response.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "loadbalancing.googleapis.com/https/backend_latencies"
    label              = "Backend latency"
    unit               = "ms"
    metricBin          = "['https']"
    valuetype          = "DISTRIBUTION"

  }
  backend_request_bytes_count = {
    type               = "delta"
    description        = <<-EOF
                    The number of bytes sent as requests from external HTTPS load balancer to backends.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "loadbalancing.googleapis.com/https/backend_request_bytes_count"
    label              = "Backend Request Bytes"
    unit               = "By"
    metricBin          = "['https']"
    valuetype          = "INT64"

  }
  backend_request_count = {
    type               = "delta"
    description        = <<-EOF
                    The number of requests served by backends of external HTTPS load balancer.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "loadbalancing.googleapis.com/https/backend_request_count"
    label              = "Backend Request Count"
    unit               = "1"
    metricBin          = "['https']"
    valuetype          = "INT64"

  }
  backend_response_bytes_count = {
    type               = "delta"
    description        = <<-EOF
                    The number of bytes sent as responses from backends or cache to external HTTPS load balancer.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "loadbalancing.googleapis.com/https/backend_response_bytes_count"
    label              = "Backend Response Bytes"
    unit               = "By"
    metricBin          = "['https']"
    valuetype          = "INT64"

  }
  backend_latencies = {
    type               = "delta"
    description        = <<-EOF
                    A distribution of the latency calculated from when the request was sent by the proxy to the backend until the proxy received from the backend the last byte of response. Sampled every 60 seconds. After sampling, data is not visible for up to 210 seconds.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "loadbalancing.googleapis.com/https/external/regional/backend_latencies"
    label              = "Backend latencies"
    unit               = "ms"
    metricBin          = "['']"
    valuetype          = "DISTRIBUTION"

  }
  request_bytes_count = {
    type               = "delta"
    description        = <<-EOF
                    The number of bytes sent as requests from clients to HTTP/S load balancer. Sampled every 60 seconds. After sampling, data is not visible for up to 90 seconds.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "loadbalancing.googleapis.com/https/external/regional/request_bytes_count"
    label              = "Request bytes"
    unit               = "By"
    metricBin          = "['']"
    valuetype          = "INT64"

  }
  request_count = {
    type               = "delta"
    description        = <<-EOF
                    The number of requests served by HTTP/S load balancer. Sampled every 60 seconds. After sampling, data is not visible for up to 90 seconds.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "loadbalancing.googleapis.com/https/external/regional/request_count"
    label              = "Request count"
    unit               = "1"
    metricBin          = "['']"
    valuetype          = "INT64"

  }
  response_bytes_count = {
    type               = "delta"
    description        = <<-EOF
                    The number of bytes sent as responses from HTTP/S load balancer to clients. Sampled every 60 seconds. After sampling, data is not visible for up to 90 seconds.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "loadbalancing.googleapis.com/https/external/regional/response_bytes_count"
    label              = "Response bytes"
    unit               = "By"
    metricBin          = "['']"
    valuetype          = "INT64"

  }
  total_latencies = {
    type               = "delta"
    description        = <<-EOF
                    A distribution of the latency calculated from when the request was received by the proxy until the proxy got ACK from client on last response byte. Sampled every 60 seconds. After sampling, data is not visible for up to 90 seconds.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "loadbalancing.googleapis.com/https/external/regional/total_latencies"
    label              = "Total latencies"
    unit               = "ms"
    metricBin          = "['']"
    valuetype          = "DISTRIBUTION"

  }
  frontend_tcp_rtt = {
    type               = "delta"
    description        = <<-EOF
                    A distribution of the RTT measured for each connection between client and proxy.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "loadbalancing.googleapis.com/https/frontend_tcp_rtt"
    label              = "Frontend RTT"
    unit               = "ms"
    metricBin          = "['https']"
    valuetype          = "DISTRIBUTION"

  }
  internal_backend_latencies = {
    type               = "delta"
    description        = <<-EOF
                    A distribution of the latency calculated from when the request was sent by the internal HTTPS load balancer proxy to the backend until the proxy received from the backend the last byte of response. Sampled every 60 seconds. After sampling, data is not visible for up to 90 seconds.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "internal"
    google_metric_path = "loadbalancing.googleapis.com/https/internal/backend_latencies"
    label              = "Backend latencies"
    unit               = "ms"
    metricBin          = "['https']"
    valuetype          = "DISTRIBUTION"

  }
  internal_request_bytes_count = {
    type               = "delta"
    description        = <<-EOF
                    The number of bytes sent as requests from clients to internal HTTPS load balancer. Sampled every 60 seconds. After sampling, data is not visible for up to 90 seconds.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "internal"
    google_metric_path = "loadbalancing.googleapis.com/https/internal/request_bytes_count"
    label              = "Request bytes"
    unit               = "By"
    metricBin          = "['https']"
    valuetype          = "INT64"

  }
  internal_request_count = {
    type               = "delta"
    description        = <<-EOF
                    The number of requests served by internal HTTPS load balancer. Sampled every 60 seconds. After sampling, data is not visible for up to 90 seconds.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "internal"
    google_metric_path = "loadbalancing.googleapis.com/https/internal/request_count"
    label              = "Request count"
    unit               = "1"
    metricBin          = "['https']"
    valuetype          = "INT64"

  }
  internal_response_bytes_count = {
    type               = "delta"
    description        = <<-EOF
                    The number of bytes sent as responses from internal HTTPS load balancer to clients. Sampled every 60 seconds. After sampling, data is not visible for up to 90 seconds.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "internal"
    google_metric_path = "loadbalancing.googleapis.com/https/internal/response_bytes_count"
    label              = "Response bytes"
    unit               = "By"
    metricBin          = "['https']"
    valuetype          = "INT64"

  }
  internal_total_latencies = {
    type               = "delta"
    description        = <<-EOF
                    A distribution of the latency calculated from when the request was received by the internal HTTPS load balancer proxy until the proxy got ACK from client on last response byte. Sampled every 60 seconds. After sampling, data is not visible for up to 90 seconds.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "internal"
    google_metric_path = "loadbalancing.googleapis.com/https/internal/total_latencies"
    label              = "Total latencies"
    unit               = "ms"
    metricBin          = "['https']"
    valuetype          = "DISTRIBUTION"

  }
  request_bytes_count = {
    type               = "delta"
    description        = <<-EOF
                    The number of bytes sent as requests from clients to external HTTPS load balancer.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "loadbalancing.googleapis.com/https/request_bytes_count"
    label              = "Request bytes"
    unit               = "By"
    metricBin          = "['https']"
    valuetype          = "INT64"

  }
  request_count = {
    type               = "delta"
    description        = <<-EOF
                    The number of requests served by external HTTPS load balancer.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "loadbalancing.googleapis.com/https/request_count"
    label              = "Request count"
    unit               = "1"
    metricBin          = "['https']"
    valuetype          = "INT64"

  }
  response_bytes_count = {
    type               = "delta"
    description        = <<-EOF
                    The number of bytes sent as responses from external HTTPS load balancer to clients.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "loadbalancing.googleapis.com/https/response_bytes_count"
    label              = "Response bytes"
    unit               = "By"
    metricBin          = "['https']"
    valuetype          = "INT64"

  }
  total_latencies = {
    type               = "delta"
    description        = <<-EOF
                    A distribution of the latency calculated from when the request was received by the external HTTPS load balancer proxy until the proxy got ACK from client on last response byte.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "loadbalancing.googleapis.com/https/total_latencies"
    label              = "Total latency"
    unit               = "ms"
    metricBin          = "['https']"
    valuetype          = "DISTRIBUTION"

  }
  external_egress_bytes_count = {
    type               = "delta"
    description        = <<-EOF
                    The number of bytes sent from the backend of the external network load balancer to the client. For TCP flows, this metric counts the bytes on the application stream only.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "external"
    google_metric_path = "loadbalancing.googleapis.com/l3/external/egress_bytes_count"
    label              = "Egress bytes count"
    unit               = "By"
    metricBin          = "['l3']"
    valuetype          = "INT64"

  }
  external_egress_packets_count = {
    type               = "delta"
    description        = <<-EOF
                    The number of packets sent from the backend of the external network load balancer to the client.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "external"
    google_metric_path = "loadbalancing.googleapis.com/l3/external/egress_packets_count"
    label              = "Egress packets count"
    unit               = "1"
    metricBin          = "['l3']"
    valuetype          = "INT64"

  }
  external_ingress_bytes_count = {
    type               = "delta"
    description        = <<-EOF
                    The number of bytes sent from the client to the backend of the external network load balancer. For TCP flows, this metric counts the bytes on the application stream only.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "external"
    google_metric_path = "loadbalancing.googleapis.com/l3/external/ingress_bytes_count"
    label              = "Ingress bytes count"
    unit               = "By"
    metricBin          = "['l3']"
    valuetype          = "INT64"

  }
  external_ingress_packets_count = {
    type               = "delta"
    description        = <<-EOF
                    The number of packets sent from the client to the backend of the external network load balancer.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "external"
    google_metric_path = "loadbalancing.googleapis.com/l3/external/ingress_packets_count"
    label              = "Ingress packets count"
    unit               = "1"
    metricBin          = "['l3']"
    valuetype          = "INT64"

  }
  external_rtt_latencies = {
    type               = "delta"
    description        = <<-EOF
                    A distribution of the round trip time latency, measured over TCP connections for the external network load balancer.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "external"
    google_metric_path = "loadbalancing.googleapis.com/l3/external/rtt_latencies"
    label              = "RTT latencies"
    unit               = "ms"
    metricBin          = "['l3']"
    valuetype          = "DISTRIBUTION"

  }
  internal_egress_bytes_count = {
    type               = "delta"
    description        = <<-EOF
                    The number of bytes sent from internal TCP/UDP load balancer backend to client for TCP flows it's counting bytes on application stream only.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "internal"
    google_metric_path = "loadbalancing.googleapis.com/l3/internal/egress_bytes_count"
    label              = "Egress bytes"
    unit               = "By"
    metricBin          = "['l3']"
    valuetype          = "INT64"

  }
  internal_egress_packets_count = {
    type               = "delta"
    description        = <<-EOF
                    The number of packets sent from internal TCP/UDP load balancer backend to client of the flow.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "internal"
    google_metric_path = "loadbalancing.googleapis.com/l3/internal/egress_packets_count"
    label              = "Egress packets"
    unit               = "1"
    metricBin          = "['l3']"
    valuetype          = "INT64"

  }
  internal_ingress_bytes_count = {
    type               = "delta"
    description        = <<-EOF
                    The number of bytes sent from client to internal TCP/UDP load balancer backend for TCP flows it's counting bytes on application stream only.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "internal"
    google_metric_path = "loadbalancing.googleapis.com/l3/internal/ingress_bytes_count"
    label              = "Ingress bytes"
    unit               = "By"
    metricBin          = "['l3']"
    valuetype          = "INT64"

  }
  internal_ingress_packets_count = {
    type               = "delta"
    description        = <<-EOF
                    The number of packets sent from client to internal TCP/UDP load balancer backend.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "internal"
    google_metric_path = "loadbalancing.googleapis.com/l3/internal/ingress_packets_count"
    label              = "Ingress packets"
    unit               = "1"
    metricBin          = "['l3']"
    valuetype          = "INT64"

  }
  internal_rtt_latencies = {
    type               = "delta"
    description        = <<-EOF
                    A distribution of RTT measured over TCP connections for internal TCP/UDP load balancer flows.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "internal"
    google_metric_path = "loadbalancing.googleapis.com/l3/internal/rtt_latencies"
    label              = "RTT latencies"
    unit               = "ms"
    metricBin          = "['l3']"
    valuetype          = "DISTRIBUTION"

  }
  egress_bytes_count = {
    type               = "delta"
    description        = <<-EOF
                    Number of bytes sent from VM to client using proxy. Sampled every 60 seconds. After sampling, data is not visible for up to 210 seconds.
                EOF
    launchStage        = "BETA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "loadbalancing.googleapis.com/l4_proxy/egress_bytes_count"
    label              = "Egress bytes"
    unit               = "By"
    metricBin          = "['l4_proxy']"
    valuetype          = "INT64"

  }
  ingress_bytes_count = {
    type               = "delta"
    description        = <<-EOF
                    Number of bytes sent from client to VM using proxy. Sampled every 60 seconds. After sampling, data is not visible for up to 210 seconds.
                EOF
    launchStage        = "BETA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "loadbalancing.googleapis.com/l4_proxy/ingress_bytes_count"
    label              = "Ingress bytes"
    unit               = "By"
    metricBin          = "['l4_proxy']"
    valuetype          = "INT64"

  }
  tcp_closed_connections_count = {
    type               = "delta"
    description        = <<-EOF
                    Number of connections that were terminated over TCP proxy or SSL proxy load balancer. Sampled every 60 seconds. After sampling, data is not visible for up to 210 seconds.
                EOF
    launchStage        = "BETA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "tcp"
    google_metric_path = "loadbalancing.googleapis.com/l4_proxy/tcp/closed_connections_count"
    label              = "Closed connections"
    unit               = "1"
    metricBin          = "['l4_proxy']"
    valuetype          = "INT64"

  }
  closed_connections = {
    type               = "delta"
    description        = <<-EOF
                    Number of connections that were terminated over TCP proxy or SSL proxy load balancer.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "loadbalancing.googleapis.com/tcp_ssl_proxy/closed_connections"
    label              = "Closed connections"
    unit               = "1"
    metricBin          = "['tcp_ssl_proxy']"
    valuetype          = "INT64"

  }
  egress_bytes_count = {
    type               = "delta"
    description        = <<-EOF
                    Number of bytes sent from VM to client using proxy.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "loadbalancing.googleapis.com/tcp_ssl_proxy/egress_bytes_count"
    label              = "Egress bytes"
    unit               = "By"
    metricBin          = "['tcp_ssl_proxy']"
    valuetype          = "INT64"

  }
  frontend_tcp_rtt = {
    type               = "delta"
    description        = <<-EOF
                    A distribution of the smoothed RTT in ms measured by the proxy's TCP stack, each minute application layer bytes pass from proxy to client.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "loadbalancing.googleapis.com/tcp_ssl_proxy/frontend_tcp_rtt"
    label              = "Frontend RTT"
    unit               = "ms"
    metricBin          = "['tcp_ssl_proxy']"
    valuetype          = "DISTRIBUTION"

  }
  ingress_bytes_count = {
    type               = "delta"
    description        = <<-EOF
                    Number of bytes sent from client to VM using proxy.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "loadbalancing.googleapis.com/tcp_ssl_proxy/ingress_bytes_count"
    label              = "Ingress bytes"
    unit               = "By"
    metricBin          = "['tcp_ssl_proxy']"
    valuetype          = "INT64"

  }
  new_connections = {
    type               = "delta"
    description        = <<-EOF
                    Number of connections that were created over TCP proxy or SSL proxy load balancer.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "loadbalancing.googleapis.com/tcp_ssl_proxy/new_connections"
    label              = "New connections opened"
    unit               = "1"
    metricBin          = "['tcp_ssl_proxy']"
    valuetype          = "INT64"

  }
  open_connections = {
    type               = "gauge"
    description        = <<-EOF
                    Current number of outstanding connections through the TCP proxy or SSL proxy load balancer.
                EOF
    launchStage        = "GA"
    rollup             = "avg"
    aggregate          = "sum"
    metricCategory     = "none"
    google_metric_path = "loadbalancing.googleapis.com/tcp_ssl_proxy/open_connections"
    label              = "Open Connections"
    unit               = "1"
    metricBin          = "['tcp_ssl_proxy']"
    valuetype          = "INT64"

  }
} }