name: Publish prerelease
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    uses: observeinc/.github/.github/workflows/terraform-observe_prerelease.yaml@arthur/release-fix-rename
    secrets: inherit
  with:
      repo-name-slack: "terraform-observe-google"
