name: Sync to Template Repo

on:
  # Run at 9am PST each Monday
  workflow_dispatch:
  schedule:
    - cron: "0 16 * * 1"

jobs:
  template-sync:
    uses: observeinc/.github/.github/workflows/terraform-observe_sync-from-template-repo.yaml@main
    secrets: inherit
    with:
      BASE_BRANCH: "main"
      HEAD_BRANCH: "chore/sync-from-template"
      GIT_AUTHOR_NAME: "${{ github.repository_owner }}"
      GIT_AUTHOR_EMAIL: "${{ github.repository_owner }}@users.noreply.github.com"
      REPO_TEMPLATE: "observeinc/terraform-observe-example"
      THIS_REPO: "${{ github.repository }}"